[package]
authors = ["Marcel Müller <neikos@neikos.email>"]
name = "shoppe"
version = "0.1.0"

[dependencies]
iron = "0.3.0"
logger = "0.0.3"
maud = "0.8.1"
maud_macros = "0.8.1"
mount = "0.1.0"
router = "0.1.1"
time = "0.1.35"
